# Base image
FROM golang:1.12.5
# Get fswatch for hot reload
RUN go get github.com/codeskyblue/fswatch
WORKDIR /go/src/github.com/josepablo93/api

# Copy the fswatch config file to the container
COPY ./.fsw.yml /.fsw.yml

# Hot reload
CMD fswatch -config /.fsw.yml 
